chore: remove exact error positions from ts-snapshots
in order to have less noise and to be able to actual infer something meaningful
from the snapshot-diffs it seems like a good idea to remove the exact position.
so:

```
   ERROR: /packages/@extension-kid/data-layer/__tests__/dataLayer-test.ts:63:1 - A maximum of 1 class per file is allowed.
->        /packages/@extension-kid/data-layer/__tests__/dataLayer-test.ts - A maximum of 1 class per file is allowed.

   plugins/tracking/actions/__tests__/Actions-test.ts(52,21): error TS2339: Property 'analytics' does not exist on type 'Global'.
-> plugins/tracking/actions/__tests__/Actions-test.ts: error TS2339: Property 'analytics' does not exist on type 'Global'.
```